//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiDiscoveryMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tab_Exobiology {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tab_Exobiology() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiDiscoveryMonitor.Properties.Tab_Exobiology", typeof(Tab_Exobiology).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Bios_Distance {
            get {
                return ResourceManager.GetString("Bios_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genus.
        /// </summary>
        public static string Bios_Genus {
            get {
                return ResourceManager.GetString("Bios_Genus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string Bios_Samples {
            get {
                return ResourceManager.GetString("Bios_Samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        public static string Bios_Species {
            get {
                return ResourceManager.GetString("Bios_Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Bios_State {
            get {
                return ResourceManager.GetString("Bios_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Bios_Value {
            get {
                return ResourceManager.GetString("Bios_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant.
        /// </summary>
        public static string Bios_Variant {
            get {
                return ResourceManager.GetString("Bios_Variant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Prediction Update.
        /// </summary>
        public static string Button_Predict {
            get {
                return ResourceManager.GetString("Button_Predict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Display.
        /// </summary>
        public static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Body.
        /// </summary>
        public static string CurrentBody {
            get {
                return ResourceManager.GetString("CurrentBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Body ID.
        /// </summary>
        public static string CurrentBodyId {
            get {
                return ResourceManager.GetString("CurrentBodyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current System.
        /// </summary>
        public static string CurrentSystem {
            get {
                return ResourceManager.GetString("CurrentSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bios.
        /// </summary>
        public static string Planet_Bios {
            get {
                return ResourceManager.GetString("Planet_Bios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Planet_Done {
            get {
                return ResourceManager.GetString("Planet_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planet.
        /// </summary>
        public static string Planet_Planet {
            get {
                return ResourceManager.GetString("Planet_Planet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1.
        /// </summary>
        public static string Samples_1 {
            get {
                return ResourceManager.GetString("Samples_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #2.
        /// </summary>
        public static string Samples_2 {
            get {
                return ResourceManager.GetString("Samples_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #3.
        /// </summary>
        public static string Samples_3 {
            get {
                return ResourceManager.GetString("Samples_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Samples_Latitude {
            get {
                return ResourceManager.GetString("Samples_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Samples_Longitude {
            get {
                return ResourceManager.GetString("Samples_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string Samples_Sample {
            get {
                return ResourceManager.GetString("Samples_Sample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to species.
        /// </summary>
        public static string species {
            get {
                return ResourceManager.GetString("species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exobiology.
        /// </summary>
        public static string Tab_Title {
            get {
                return ResourceManager.GetString("Tab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        public static string The {
            get {
                return ResourceManager.GetString("The", resourceCulture);
            }
        }
    }
}
