//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiDiscoveryMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tab_General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tab_General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiDiscoveryMonitor.Properties.Tab_General", typeof(Tab_General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Exobiology tab data will automatically update depending on the contextual body. For example if you target a planet it will show the data for that planet. If you scan a biological on a planet it will show data for that planet..
        /// </summary>
        public static string Description_Exobiology {
            get {
                return ResourceManager.GetString("Description_Exobiology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebulae and Guardian Sites will not automatically update when the system changes. Press the associated button in those tabs to see the data..
        /// </summary>
        public static string Description_NebulaeGuardian {
            get {
                return ResourceManager.GetString("Description_NebulaeGuardian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The System Address should automatically update whenever the current system changes. The tools on the different tabs rely on these coordinates and they can be manually changed to run the tools on different locations. The Region is not automatically updated..
        /// </summary>
        public static string Description_SystemAddress {
            get {
                return ResourceManager.GetString("Description_SystemAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These tabs allow configuration of the codex discoveries, exobiology and to a lesser extend geology. They change how the scripts work without needing to modify the scripts directly. Most settings have tooltips to briefly explain what they do..
        /// </summary>
        public static string Description_Tabs {
            get {
                return ResourceManager.GetString("Description_Tabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Current.
        /// </summary>
        public static string GetCurrent {
            get {
                return ResourceManager.GetString("GetCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Region.
        /// </summary>
        public static string GetRegion {
            get {
                return ResourceManager.GetString("GetRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Bark Mounds.
        /// </summary>
        public static string IgnoreBarkMounds {
            get {
                return ResourceManager.GetString("IgnoreBarkMounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Brain Trees.
        /// </summary>
        public static string IgnoreBrainTrees {
            get {
                return ResourceManager.GetString("IgnoreBrainTrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Crystal Shards.
        /// </summary>
        public static string IgnoreCrystalShards {
            get {
                return ResourceManager.GetString("IgnoreCrystalShards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Tubers.
        /// </summary>
        public static string IgnoreTubers {
            get {
                return ResourceManager.GetString("IgnoreTubers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These can often give false predictions due to their broad conditions..
        /// </summary>
        public static string LegacyDescription {
            get {
                return ResourceManager.GetString("LegacyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Predictions.
        /// </summary>
        public static string LegacyPredictions {
            get {
                return ResourceManager.GetString("LegacyPredictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Address.
        /// </summary>
        public static string SystemAddress {
            get {
                return ResourceManager.GetString("SystemAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Tab_Title {
            get {
                return ResourceManager.GetString("Tab_Title", resourceCulture);
            }
        }
    }
}
