//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiDiscoveryMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tab_Guardian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tab_Guardian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiDiscoveryMonitor.Properties.Tab_Guardian", typeof(Tab_Guardian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Nearest Guardian Sites.
        /// </summary>
        public static string Button_GetNearest {
            get {
                return ResourceManager.GetString("Button_GetNearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy this system name to your clipboard.
        /// </summary>
        public static string copy_system_button_tooltip {
            get {
                return ResourceManager.GetString("copy_system_button_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beacons.
        /// </summary>
        public static string Filter_Beacons {
            get {
                return ResourceManager.GetString("Filter_Beacons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module BP.
        /// </summary>
        public static string Filter_ModuleBP {
            get {
                return ResourceManager.GetString("Filter_ModuleBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruins.
        /// </summary>
        public static string Filter_Ruins {
            get {
                return ResourceManager.GetString("Filter_Ruins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structures.
        /// </summary>
        public static string Filter_Structures {
            get {
                return ResourceManager.GetString("Filter_Structures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel BP.
        /// </summary>
        public static string Filter_VesselBP {
            get {
                return ResourceManager.GetString("Filter_VesselBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon BP.
        /// </summary>
        public static string Filter_WeaponBP {
            get {
                return ResourceManager.GetString("Filter_WeaponBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Sites.
        /// </summary>
        public static string GuardianSites {
            get {
                return ResourceManager.GetString("GuardianSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blueprint.
        /// </summary>
        public static string GuardianSites_Blueprint {
            get {
                return ResourceManager.GetString("GuardianSites_Blueprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string GuardianSites_Body {
            get {
                return ResourceManager.GetString("GuardianSites_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string GuardianSites_Distance {
            get {
                return ResourceManager.GetString("GuardianSites_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string GuardianSites_System {
            get {
                return ResourceManager.GetString("GuardianSites_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string GuardianSites_Type {
            get {
                return ResourceManager.GetString("GuardianSites_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Distance.
        /// </summary>
        public static string MaxDistance {
            get {
                return ResourceManager.GetString("MaxDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Results.
        /// </summary>
        public static string MaxResults {
            get {
                return ResourceManager.GetString("MaxResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Sites.
        /// </summary>
        public static string Tab_Title {
            get {
                return ResourceManager.GetString("Tab_Title", resourceCulture);
            }
        }
    }
}
