//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EddiDiscoveryMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tab_Nebulae {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tab_Nebulae() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EddiDiscoveryMonitor.Properties.Tab_Nebulae", typeof(Tab_Nebulae).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Nearest Nebula.
        /// </summary>
        public static string Button_GetNearest {
            get {
                return ResourceManager.GetString("Button_GetNearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Distance.
        /// </summary>
        public static string MaxDistance {
            get {
                return ResourceManager.GetString("MaxDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Results.
        /// </summary>
        public static string MaxResults {
            get {
                return ResourceManager.GetString("MaxResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Nebulae.
        /// </summary>
        public static string NearestNebulae {
            get {
                return ResourceManager.GetString("NearestNebulae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string NearestNebulae_Diameter {
            get {
                return ResourceManager.GetString("NearestNebulae_Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string NearestNebulae_Distance {
            get {
                return ResourceManager.GetString("NearestNebulae_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Visited.
        /// </summary>
        public static string NearestNebulae_Edit {
            get {
                return ResourceManager.GetString("NearestNebulae_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string NearestNebulae_Modify {
            get {
                return ResourceManager.GetString("NearestNebulae_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NearestNebulae_Name {
            get {
                return ResourceManager.GetString("NearestNebulae_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string NearestNebulae_Reference {
            get {
                return ResourceManager.GetString("NearestNebulae_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        public static string NearestNebulae_Toggle {
            get {
                return ResourceManager.GetString("NearestNebulae_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string NearestNebulae_Type {
            get {
                return ResourceManager.GetString("NearestNebulae_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited.
        /// </summary>
        public static string NearestNebulae_Visited {
            get {
                return ResourceManager.GetString("NearestNebulae_Visited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nebulae.
        /// </summary>
        public static string Tab_Title {
            get {
                return ResourceManager.GetString("Tab_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type filter.
        /// </summary>
        public static string TypeFilter {
            get {
                return ResourceManager.GetString("TypeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string TypeFilter_All {
            get {
                return ResourceManager.GetString("TypeFilter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planetary.
        /// </summary>
        public static string TypeFilter_Planetary {
            get {
                return ResourceManager.GetString("TypeFilter_Planetary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real.
        /// </summary>
        public static string TypeFilter_Real {
            get {
                return ResourceManager.GetString("TypeFilter_Real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string TypeFilter_Standard {
            get {
                return ResourceManager.GetString("TypeFilter_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited filter.
        /// </summary>
        public static string VisitedFilter {
            get {
                return ResourceManager.GetString("VisitedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string VisitedFilter_All {
            get {
                return ResourceManager.GetString("VisitedFilter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Visited.
        /// </summary>
        public static string VisitedFilter_NotVisited {
            get {
                return ResourceManager.GetString("VisitedFilter_NotVisited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited.
        /// </summary>
        public static string VisitedFilter_Visited {
            get {
                return ResourceManager.GetString("VisitedFilter_Visited", resourceCulture);
            }
        }
    }
}
